version: '3.8'
services:
  db:
    image: postgres:15
    env_file:
      - .env.production
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    build: .
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  db-data: